### ISSUE TITLE
Support for projects with minimum deployment target less that iOS 17.

### ISSUE THREAD

**Issue by denandreychuk** [joogps/Glur#4]
For now, it's strictly iOS 17, which makes it impossible to add to projects with a lower minimum deployment target (MDT). What we can do is mark the modifier with `@available` and let the caller side decide how to handle it in older versions.

For example, it can be handled as a regular `.blur()` in older versions.

**Comment by denandreychuk** [comment]
For example, it can be handled as a regular `.blur` in older versions.

**Comment by joogps** [comment]
Hey there, Dan!

Thanks for the suggestion. That's actually a great idea that I hadn't really considered. I'll work on it for the 1.0 release.

**Comment by joogps** [comment]
Done as of b805ea48206c5cbca98ccd54c8424e09847bcab6! Thank you for your contribution @denandreychuk!

What I did was actually make the `.glur()` modifier work from iOS 13.0 upwards using a "compatibility effect" by layering a blurred version of the view on top of itself and masking it with a linear gradient.

Just beware that, of course, this effect won't be as aesthetically pleasing/efficient/versatile as the iOS 17.0 implementation, but, in some cases, it might work. And, considering how the iOS 17.0 user base is growing, hopefully that won't be as much of an issue soon.
