### ISSUE TITLE
Drop/use compatibility mode for watchOS targets

### ISSUE THREAD

**Issue by vincentneo** [joogps/Glur#6]
It appears that the SwiftUI shader support isn't available for watchOS 10.
(Reference: https://developer.apple.com/documentation/swiftui/shaderlibrary)

However, Glur's main metal-based modifier is set as available for watchOS 10, which is incorrect, resulting in a set of 'unavailable' errors when attempting to build for use in watchOS.

**Comment by joogps** [comment]
Thank you so much for pointing that out, Vincent!

I didn't test the code on an Apple Watch (I didn't have a 10.0 runtime downloaded haha) and just assumed that the SwiftUI shader modifiers were available on it like the other platforms.

It has been fixed as of [v1.0.1](https://github.com/joogps/Glur/releases/tag/1.0.1).
